version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    networks:
      - bluesburguer-network
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-1}
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - PERSISTENCE=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/etc/localstack/init/ready.d"  # ready hook
  
  consul:
    image: hashicorp/consul:latest
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - bluesburguer-network
    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:8500/v1/status/leader || exit 1
      test: ["CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader"]
      interval: 1m
      timeout: 3s
      retries: 60

networks:
  bluesburguer-network:
    driver: bridge

volumes:
  db_app:
